version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: ethara_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: inventory_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ethara_backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:${DB_PASSWORD}@db:5432/inventory_db
      CORS_ORIGINS: "http://localhost:5173,http://localhost:8080,http://localhost"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=https://ethara-ai-1-b2xp.onrender.com
    container_name: ethara_frontend
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  pgdata:
